<RootWidget>
	Label:
		size_hint: .1, .1				# Dimensões percentuais
		pos_hint: {'x': .5, 'y': .90}	# Localização percentuais
		text: 'Hello World!'
		font_size: "20sp"

	Button:
		size_hint: None, None
		size: 350, 50
		pos: 100, 350
		text: "px"
		
	Button:
		size_hint: None, None
		size: dp(350), dp(50)
		pos: dp(100), dp(270)
		text: "dp"
				
	Button:
		size_hint: .5, .09
		pos_hint: {'x': .5, 'y': .1}
		text: "%"
